// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/dingconnect-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"account_lookup | balance | cancel_transfer | country | currency | error_code_description | estimate_price | list_transfer_record | lookup_bill | product | product_description | promotion | promotion_description | provider | provider_status | region | send_transfer"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.DingconnectSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "dingconnect_list",
		Description: "List records from Dingconnect. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "dingconnect_load",
		Description: "Load a single record from Dingconnect. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.DingconnectSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.DingconnectSDK, name string) (sdk.DingconnectEntity, error) {
	switch strings.ToLower(name) {
	case "account_lookup":
		return client.AccountLookup(nil), nil
	case "balance":
		return client.Balance(nil), nil
	case "cancel_transfer":
		return client.CancelTransfer(nil), nil
	case "country":
		return client.Country(nil), nil
	case "currency":
		return client.Currency(nil), nil
	case "error_code_description":
		return client.ErrorCodeDescription(nil), nil
	case "estimate_price":
		return client.EstimatePrice(nil), nil
	case "list_transfer_record":
		return client.ListTransferRecord(nil), nil
	case "lookup_bill":
		return client.LookupBill(nil), nil
	case "product":
		return client.Product(nil), nil
	case "product_description":
		return client.ProductDescription(nil), nil
	case "promotion":
		return client.Promotion(nil), nil
	case "promotion_description":
		return client.PromotionDescription(nil), nil
	case "provider":
		return client.Provider(nil), nil
	case "provider_status":
		return client.ProviderStatus(nil), nil
	case "region":
		return client.Region(nil), nil
	case "send_transfer":
		return client.SendTransfer(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
