<?php
declare(strict_types=1);

// Dingconnect SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

DingconnectUtility::setRegistrar(function (DingconnectUtility $u): void {
    $u->clean = [DingconnectClean::class, 'call'];
    $u->done = [DingconnectDone::class, 'call'];
    $u->make_error = [DingconnectMakeError::class, 'call'];
    $u->feature_add = [DingconnectFeatureAdd::class, 'call'];
    $u->feature_hook = [DingconnectFeatureHook::class, 'call'];
    $u->feature_init = [DingconnectFeatureInit::class, 'call'];
    $u->fetcher = [DingconnectFetcher::class, 'call'];
    $u->make_fetch_def = [DingconnectMakeFetchDef::class, 'call'];
    $u->make_context = [DingconnectMakeContext::class, 'call'];
    $u->make_options = [DingconnectMakeOptions::class, 'call'];
    $u->make_request = [DingconnectMakeRequest::class, 'call'];
    $u->make_response = [DingconnectMakeResponse::class, 'call'];
    $u->make_result = [DingconnectMakeResult::class, 'call'];
    $u->make_point = [DingconnectMakePoint::class, 'call'];
    $u->make_spec = [DingconnectMakeSpec::class, 'call'];
    $u->make_url = [DingconnectMakeUrl::class, 'call'];
    $u->param = [DingconnectParam::class, 'call'];
    $u->prepare_auth = [DingconnectPrepareAuth::class, 'call'];
    $u->prepare_body = [DingconnectPrepareBody::class, 'call'];
    $u->prepare_headers = [DingconnectPrepareHeaders::class, 'call'];
    $u->prepare_method = [DingconnectPrepareMethod::class, 'call'];
    $u->prepare_params = [DingconnectPrepareParams::class, 'call'];
    $u->prepare_path = [DingconnectPreparePath::class, 'call'];
    $u->prepare_query = [DingconnectPrepareQuery::class, 'call'];
    $u->graphql_body = [DingconnectGraphql::class, 'body'];
    $u->graphql_errors = [DingconnectGraphql::class, 'errors'];
    $u->result_basic = [DingconnectResultBasic::class, 'call'];
    $u->result_body = [DingconnectResultBody::class, 'call'];
    $u->result_headers = [DingconnectResultHeaders::class, 'call'];
    $u->transform_request = [DingconnectTransformRequest::class, 'call'];
    $u->transform_response = [DingconnectTransformResponse::class, 'call'];
});
